export const CHECK_USER_LOGIN_STATUS = 'CHECK_USER_LOGIN_STATUS';
export const START_CHECKING_USER_LOGIN_STATUS = 'START_CHECKING_USER_LOGIN_STATUS';
export const COMPLETE_CHECKING_USER_LOGIN_STATUS = 'COMPLETE_CHECKING_USER_LOGIN_STATUS';
export const FAIL_CHECKING_USER_LOGIN_STATUS = 'FAIL_CHECKING_USER_LOGIN_STATUS';

export const SIGN_USER_UP = 'SIGN_USER_UP';
export const START_SIGNING_USER_UP = 'START_SIGNING_USER_UP';
export const COMPLETE_SIGNING_USER_UP = 'COMPLETE_SIGNING_USER_UP';
export const FAIL_SIGNING_USER_UP = 'FAIL_SIGNING_USER_UP';

export const LOG_USER_IN = 'LOG_USER_IN';
export const START_LOGGING_USER_IN = 'START_LOGGING_USER_IN';
export const COMPLETE_LOGGING_USER_IN = 'COMPLETE_LOGGING_USER_IN';
export const FAIL_LOGGING_USER_IN = 'FAIL_LOGGING_USER_IN';

export const LOG_USER_OUT = 'LOG_USER_OUT';
export const START_LOGGING_USER_OUT = 'START_LOGGING_USER_OUT';
export const COMPLETE_LOGGING_USER_OUT = 'COMPLETE_LOGGING_USER_OUT';
export const FAIL_LOGGING_USER_OUT = 'FAIL_LOGGING_USER_OUT';
