export const FETCH_GROUPS = 'FETCH_GROUPS';
export const START_FETCHING_GROUPS = 'START_FETCHING_GROUPS';
export const COMPLETE_FETCHING_GROUPS = 'COMPLETE_FETCHING_GROUPS';
export const FAIL_FETCHING_GROUPS = 'FAIL_FETCHING_GROUPS';

export const INVALIDATE_GROUPS = 'INVALIDATE_GROUPS';

export const LOAD_NEW_GROUP_DETAILS = 'LOAD_NEW_GROUP_DETAILS';
export const LOAD_GROUP_DETAILS = 'LOAD_GROUP_DETAILS';

export const SAVE_GROUP = 'SAVE_GROUP';
export const SET_GROUP_FORM_STATUS = 'SET_GROUP_FORM_STATUS';
export const REQUEST_GROUP_SAVE = 'REQUEST_GROUP_SAVE';
export const START_SAVING_GROUP = 'START_SAVING_GROUP';
export const ASK_CONFIRMATION_BEFORE_SAVING_GROUP = 'ASK_CONFIRMATION_BEFORE_SAVING_GROUP';
export const COMPLETE_SAVING_GROUP = 'COMPLETE_SAVING_GROUP';
export const FAIL_SAVING_GROUP = 'FAIL_SAVING_GROUP';

export const DELETE_GROUP = 'DELETE_GROUP';
export const START_DELETING_GROUP = 'START_DELETING_GROUP';
export const COMPLETE_DELETING_GROUP = 'COMPLETE_DELETING_GROUP';
export const FAIL_DELETING_GROUP = 'FAIL_DELETING_GROUP';

export const HIGHLIGHT_GROUP = 'HIGHLIGHT_GROUP';
export const REMOVE_GROUP_HIGHTLIGHT = 'REMOVE_GROUP_HIGHTLIGHT';

export const REQUEST_GROUP_SELECTION = 'REQUEST_GROUP_SELECTION';
export const SELECT_GROUP = 'SELECT_GROUP';
