export const FETCH_GROUPS = 'FETCH_GROUPS';
export const START_FETCHING_GROUPS = 'START_FETCHING_GROUPS';
export const COMPLETE_FETCHING_GROUPS = 'COMPLETE_FETCHING_GROUPS';
export const FAIL_FETCHING_GROUPS = 'FAIL_FETCHING_GROUPS';

export const INVALIDATE_GROUPS = 'INVALIDATE_GROUPS';

export const SAVE_GROUP = 'SAVE_GROUP';
export const START_SAVING_GROUP = 'START_SAVING_GROUP';
export const COMPLETE_SAVING_GROUP = 'COMPLETE_SAVING_GROUP';
export const FAIL_SAVING_GROUP = 'FAIL_SAVING_GROUP';

export const DELETE_GROUP = 'DELETE_GROUP';
export const START_DELETING_GROUP = 'START_DELETING_GROUP';
export const COMPLETE_DELETING_GROUP = 'COMPLETE_DELETING_GROUP';
export const FAIL_DELETING_GROUP = 'FAIL_DELETING_GROUP';
