export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const INVALIDATE_CATEGORIES = 'INVALIDATE_CATEGORIES';

export const LOAD_NEW_CATEGORY_DETAILS = 'LOAD_NEW_CATEGORY_DETAILS';
export const LOAD_CATEGORY_DETAILS = 'LOAD_CATEGORY_DETAILS';

export const SAVE_CATEGORY = 'SAVE_CATEGORY';
export const START_SAVING_CATEGORY = 'START_SAVING_CATEGORY';
export const COMPLETE_SAVING_CATEGORY = 'COMPLETE_SAVING_CATEGORY';
