export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const START_FETCHING_CATEGORIES = 'START_FETCHING_CATEGORIES';
export const COMPLETE_FETCHING_CATEGORIES = 'COMPLETE_FETCHING_CATEGORIES';
export const FAIL_FETCHING_CATEGORIES = 'FAIL_FETCHING_CATEGORIES';

export const INVALIDATE_CATEGORIES = 'INVALIDATE_CATEGORIES';

export const LOAD_NEW_CATEGORY_DETAILS = 'LOAD_NEW_CATEGORY_DETAILS';
export const LOAD_CATEGORY_DETAILS = 'LOAD_CATEGORY_DETAILS';

export const SAVE_CATEGORY = 'SAVE_CATEGORY';
export const SET_CATEGORY_FORM_STATUS = 'SET_CATEGORY_FORM_STATUS';
export const REQUEST_CATEGORY_SAVE = 'REQUEST_CATEGORY_SAVE';
export const START_SAVING_CATEGORY = 'START_SAVING_CATEGORY';
export const COMPLETE_SAVING_CATEGORY = 'COMPLETE_SAVING_CATEGORY';
export const FAIL_SAVING_CATEGORY = 'FAIL_SAVING_CATEGORY';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const START_DELETING_CATEGORY = 'START_DELETING_CATEGORY';
export const COMPLETE_DELETING_CATEGORY = 'COMPLETE_DELETING_CATEGORY';
export const FAIL_DELETING_CATEGORY = 'FAIL_DELETING_CATEGORY';

export const HIGHLIGHT_CATEGORY = 'HIGHLIGHT_CATEGORY';
export const REMOVE_CATEGORY_HIGHTLIGHT = 'REMOVE_CATEGORY_HIGHTLIGHT';
