export const FETCH_OWN_PLATFORMS = 'FETCH_OWN_PLATFORMS';
export const START_FETCHING_OWN_PLATFORMS = 'START_FETCHING_OWN_PLATFORMS';
export const COMPLETE_FETCHING_OWN_PLATFORMS = 'COMPLETE_FETCHING_OWN_PLATFORMS';
export const FAIL_FETCHING_OWN_PLATFORMS = 'FAIL_FETCHING_OWN_PLATFORMS';

export const INVALIDATE_OWN_PLATFORMS = 'INVALIDATE_OWN_PLATFORMS';

export const LOAD_NEW_OWN_PLATFORM_DETAILS = 'LOAD_NEW_OWN_PLATFORM_DETAILS';
export const LOAD_OWN_PLATFORM_DETAILS = 'LOAD_OWN_PLATFORM_DETAILS';

export const SAVE_OWN_PLATFORM = 'SAVE_OWN_PLATFORM';
export const SET_OWN_PLATFORM_FORM_STATUS = 'SET_OWN_PLATFORM_FORM_STATUS';
export const REQUEST_OWN_PLATFORM_SAVE = 'REQUEST_OWN_PLATFORM_SAVE';
export const START_SAVING_OWN_PLATFORM = 'START_SAVING_OWN_PLATFORM';
export const ASK_CONFIRMATION_BEFORE_SAVING_OWN_PLATFORM = 'ASK_CONFIRMATION_BEFORE_SAVING_OWN_PLATFORM';
export const COMPLETE_SAVING_OWN_PLATFORM = 'COMPLETE_SAVING_OWN_PLATFORM';
export const FAIL_SAVING_OWN_PLATFORM = 'FAIL_SAVING_OWN_PLATFORM';

export const DELETE_OWN_PLATFORM = 'DELETE_OWN_PLATFORM';
export const START_DELETING_OWN_PLATFORM = 'START_DELETING_OWN_PLATFORM';
export const COMPLETE_DELETING_OWN_PLATFORM = 'COMPLETE_DELETING_OWN_PLATFORM';
export const FAIL_DELETING_OWN_PLATFORM = 'FAIL_DELETING_OWN_PLATFORM';

export const HIGHLIGHT_OWN_PLATFORM = 'HIGHLIGHT_OWN_PLATFORM';
export const REMOVE_OWN_PLATFORM_HIGHTLIGHT = 'REMOVE_OWN_PLATFORM_HIGHTLIGHT';

export const REQUEST_OWN_PLATFORM_SELECTION = 'REQUEST_OWN_PLATFORM_SELECTION';
export const SELECT_OWN_PLATFORM = 'SELECT_OWN_PLATFORM';
