export const IMPORT_OLD_APP_EXPORT = 'IMPORT_OLD_APP_EXPORT';
export const START_IMPORTING_OLD_APP_EXPORT = 'START_IMPORTING_OLD_APP_EXPORT';
export const COMPLETE_IMPORTING_OLD_APP_EXPORT = 'COMPLETE_IMPORTING_OLD_APP_EXPORT';
export const FAIL_IMPORTING_OLD_APP_EXPORT = 'FAIL_IMPORTING_OLD_APP_EXPORT';
