export const START_TV_SHOW_SEASONS_HANDLING = 'START_TV_SHOW_SEASONS_HANDLING';
export const COMPLETE_TV_SHOW_SEASONS_HANDLING = 'COMPLETE_TV_SHOW_SEASONS_HANDLING';

export const LOAD_NEW_TV_SHOW_SEASON_DETAILS = 'LOAD_NEW_TV_SHOW_SEASON_DETAILS';
export const LOAD_TV_SHOW_SEASON_DETAILS = 'LOAD_TV_SHOW_SEASON_DETAILS';

export const REQUEST_TV_SHOW_SEASON_SAVE = 'REQUEST_TV_SHOW_SEASON_SAVE';
export const SAVE_TV_SHOW_SEASON = 'SAVE_TV_SHOW_SEASON';
export const SET_TV_SHOW_SEASON_FORM_STATUS = 'SET_TV_SHOW_SEASON_FORM_STATUS';
export const COMPLETE_SAVING_TV_SHOW_SEASON = 'COMPLETE_SAVING_TV_SHOW_SEASON';
export const FAIL_SAVING_TV_SHOW_SEASON = 'FAIL_SAVING_TV_SHOW_SEASON';

export const DELETE_TV_SHOW_SEASON = 'DELETE_TV_SHOW_SEASON';
export const COMPLETE_DELETING_TV_SHOW_SEASON = 'COMPLETE_DELETING_TV_SHOW_SEASON';

export const INLINE_UPDATE_TV_SHOW_SEASON = 'INLINE_UPDATE_TV_SHOW_SEASON';
export const COMPLETE_INLINE_UPDATING_TV_SHOW_SEASON = 'COMPLETE_INLINE_UPDATING_TV_SHOW_SEASON';

export const HIGHLIGHT_TV_SHOW_SEASON = 'HIGHLIGHT_TV_SHOW_SEASON';
export const REMOVE_TV_SHOW_SEASON_HIGHLIGHT = 'REMOVE_TV_SHOW_SEASON_HIGHLIGHT';
