export const OPEN_MEDIA_ITEMS_LIST = 'OPEN_MEDIA_ITEMS_LIST';

export const SEARCH_MEDIA_ITEMS = 'SEARCH_MEDIA_ITEMS';
export const FETCH_MEDIA_ITEMS = 'FETCH_MEDIA_ITEMS';
export const START_FETCHING_MEDIA_ITEMS = 'START_FETCHING_MEDIA_ITEMS';
export const COMPLETE_FETCHING_MEDIA_ITEMS = 'COMPLETE_FETCHING_MEDIA_ITEMS';
export const FAIL_FETCHING_MEDIA_ITEMS = 'FAIL_FETCHING_MEDIA_ITEMS';

export const DELETE_MEDIA_ITEM = 'DELETE_MEDIA_ITEM';
export const START_DELETING_MEDIA_ITEM = 'START_DELETING_MEDIA_ITEM';
export const COMPLETE_DELETING_MEDIA_ITEM = 'COMPLETE_DELETING_MEDIA_ITEM';
export const FAIL_DELETING_MEDIA_ITEM = 'FAIL_DELETING_MEDIA_ITEM';

export const MARK_MEDIA_ITEM_AS_ACTIVE = 'MARK_MEDIA_ITEM_AS_ACTIVE';
export const MARK_MEDIA_ITEM_AS_COMPLETE = 'MARK_MEDIA_ITEM_AS_COMPLETE';
export const MARK_MEDIA_ITEM_AS_REDO = 'MARK_MEDIA_ITEM_AS_REDO';
export const START_INLINE_UPDATING_MEDIA_ITEM = 'START_INLINE_UPDATING_MEDIA_ITEM';
export const COMPLETE_INLINE_UPDATING_MEDIA_ITEM = 'COMPLETE_INLINE_UPDATING_MEDIA_ITEM';
export const FAIL_INLINE_UPDATING_MEDIA_ITEM = 'FAIL_INLINE_UPDATING_MEDIA_ITEM';

export const HIGHLIGHT_MEDIA_ITEM = 'HIGHLIGHT_MEDIA_ITEM';
export const REMOVE_MEDIA_ITEM_HIGHTLIGHT = 'REMOVE_MEDIA_ITEM_HIGHTLIGHT';

export const START_MEDIA_ITEMS_SEARCH_MODE = 'START_MEDIA_ITEMS_SEARCH_MODE';
export const STOP_MEDIA_ITEMS_SEARCH_MODE = 'STOP_MEDIA_ITEMS_SEARCH_MODE';
