export const OPEN_MEDIA_ITEMS_LIST = 'OPEN_MEDIA_ITEMS_LIST';

export const FETCH_MEDIA_ITEMS = 'FETCH_MEDIA_ITEMS';
export const START_FETCHING_MEDIA_ITEMS = 'START_FETCHING_MEDIA_ITEMS';
export const COMPLETE_FETCHING_MEDIA_ITEMS = 'COMPLETE_FETCHING_MEDIA_ITEMS';
export const FAIL_FETCHING_MEDIA_ITEMS = 'FAIL_FETCHING_MEDIA_ITEMS';

