export const SEARCH_MEDIA_ITEMS = 'SEARCH_MEDIA_ITEMS';
export const FETCH_MEDIA_ITEMS = 'FETCH_MEDIA_ITEMS';
export const START_FETCHING_MEDIA_ITEMS = 'START_FETCHING_MEDIA_ITEMS';
export const COMPLETE_FETCHING_MEDIA_ITEMS = 'COMPLETE_FETCHING_MEDIA_ITEMS';
export const FAIL_FETCHING_MEDIA_ITEMS = 'FAIL_FETCHING_MEDIA_ITEMS';

export const DELETE_MEDIA_ITEM = 'DELETE_MEDIA_ITEM';
export const START_DELETING_MEDIA_ITEM = 'START_DELETING_MEDIA_ITEM';
export const COMPLETE_DELETING_MEDIA_ITEM = 'COMPLETE_DELETING_MEDIA_ITEM';
export const FAIL_DELETING_MEDIA_ITEM = 'FAIL_DELETING_MEDIA_ITEM';

export const MARK_MEDIA_ITEM_AS_ACTIVE = 'MARK_MEDIA_ITEM_AS_ACTIVE';
export const MARK_MEDIA_ITEM_AS_COMPLETE = 'MARK_MEDIA_ITEM_AS_COMPLETE';
export const MARK_MEDIA_ITEM_AS_REDO = 'MARK_MEDIA_ITEM_AS_REDO';
export const START_INLINE_UPDATING_MEDIA_ITEM = 'START_INLINE_UPDATING_MEDIA_ITEM';
export const COMPLETE_INLINE_UPDATING_MEDIA_ITEM = 'COMPLETE_INLINE_UPDATING_MEDIA_ITEM';
export const FAIL_INLINE_UPDATING_MEDIA_ITEM = 'FAIL_INLINE_UPDATING_MEDIA_ITEM';

export const HIGHLIGHT_MEDIA_ITEM = 'HIGHLIGHT_MEDIA_ITEM';
export const REMOVE_MEDIA_ITEM_HIGHTLIGHT = 'REMOVE_MEDIA_ITEM_HIGHTLIGHT';

export const START_MEDIA_ITEMS_SEARCH_MODE = 'START_MEDIA_ITEMS_SEARCH_MODE';
export const STOP_MEDIA_ITEMS_SEARCH_MODE = 'STOP_MEDIA_ITEMS_SEARCH_MODE';

export const START_MEDIA_ITEMS_VIEW_GROUP_MODE = 'START_MEDIA_ITEMS_VIEW_GROUP_MODE';
export const STOP_MEDIA_ITEMS_VIEW_GROUP_MODE = 'STOP_MEDIA_ITEMS_VIEW_GROUP_MODE';

export const START_MEDIA_ITEMS_SET_FILTERS_MODE = 'START_MEDIA_ITEMS_SET_FILTERS_MODE';
export const SUBMIT_MEDIA_ITEMS_FILTERS = 'SUBMIT_MEDIA_ITEMS_FILTERS';
export const STOP_MEDIA_ITEMS_SET_FILTERS_MODE = 'STOP_MEDIA_ITEMS_SET_FILTERS_MODE';

export const LOAD_NEW_MEDIA_ITEM_DETAILS = 'LOAD_NEW_MEDIA_ITEM_DETAILS';
export const LOAD_MEDIA_ITEM_DETAILS = 'LOAD_MEDIA_ITEM_DETAILS';

export const SAVE_MEDIA_ITEM = 'SAVE_MEDIA_ITEM';
export const SET_MEDIA_ITEM_FORM_STATUS = 'SET_MEDIA_ITEM_FORM_STATUS';
export const REQUEST_MEDIA_ITEM_SAVE = 'REQUEST_MEDIA_ITEM_SAVE';
export const START_SAVING_MEDIA_ITEM = 'START_SAVING_MEDIA_ITEM';
export const ASK_CONFIRMATION_BEFORE_SAVING_MEDIA_ITEM = 'ASK_CONFIRMATION_BEFORE_SAVING_MEDIA_ITEM';
export const COMPLETE_SAVING_MEDIA_ITEM = 'COMPLETE_SAVING_MEDIA_ITEM';
export const FAIL_SAVING_MEDIA_ITEM = 'FAIL_SAVING_MEDIA_ITEM';

export const SEARCH_MEDIA_ITEMS_CATALOG = 'SEARCH_MEDIA_ITEMS_CATALOG';
export const START_SEARCHING_MEDIA_ITEMS_CATALOG = 'START_SEARCHING_MEDIA_ITEMS_CATALOG';
export const COMPLETE_SEARCHING_MEDIA_ITEMS_CATALOG = 'COMPLETE_SEARCHING_MEDIA_ITEMS_CATALOG';
export const FAIL_SEARCHING_MEDIA_ITEMS_CATALOG = 'FAIL_SEARCHING_MEDIA_ITEMS_CATALOG';
export const RESET_MEDIA_ITEMS_CATALOG_SEARCH = 'RESET_MEDIA_ITEMS_CATALOG_SEARCH';

export const GET_MEDIA_ITEM_CATALOG_DETAILS = 'GET_MEDIA_ITEM_CATALOG_DETAILS';
export const START_GETTING_MEDIA_ITEM_CATALOG_DETAILS = 'START_GETTING_MEDIA_ITEM_CATALOG_DETAILS';
export const COMPLETE_GETTING_MEDIA_ITEM_CATALOG_DETAILS = 'COMPLETE_GETTING_MEDIA_ITEM_CATALOG_DETAILS';
export const FAIL_GETTING_MEDIA_ITEM_CATALOG_DETAILS = 'FAIL_GETTING_MEDIA_ITEM_CATALOG_DETAILS';
export const RESET_MEDIA_ITEM_CATALOG_DETAILS = 'RESET_MEDIA_ITEM_CATALOG_DETAILS';
